# Generated by Django 2.1.7 on 2019-04-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentandStarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whichcomment', models.CharField(blank=True, max_length=1000, null=True)),
                ('startcount', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=1000, null=True)),
                ('explain', models.CharField(blank=True, max_length=1000, null=True)),
                ('imagelist', models.CharField(blank=True, max_length=5000, null=True)),
                ('showdemo', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('productprice', models.DecimalField(decimal_places=8, default='0', max_digits=25)),
                ('pname', models.CharField(blank=True, max_length=1000, null=True)),
                ('pid', models.CharField(blank=True, max_length=1000, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=1000, null=True)),
                ('hash', models.CharField(blank=True, max_length=1000, null=True)),
                ('pubkey', models.CharField(blank=True, max_length=5000, null=True)),
                ('pid', models.CharField(blank=True, max_length=1000, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default='0', max_digits=25)),
                ('pname', models.CharField(blank=True, max_length=1000, null=True)),
                ('indexify', models.CharField(blank=True, max_length=1000, null=True)),
                ('smessage', models.CharField(blank=True, max_length=5000, null=True)),
                ('pid', models.CharField(blank=True, max_length=1000, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urltype', models.CharField(blank=True, max_length=1000, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('surname', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('ethereumaddress', models.CharField(blank=True, max_length=1000, null=True)),
                ('privatekey', models.CharField(blank=True, max_length=1000, null=True)),
                ('publickey', models.CharField(blank=True, max_length=5000, null=True)),
                ('moneycode', models.CharField(blank=True, max_length=1000, null=True)),
                ('random_base32', models.CharField(blank=True, max_length=1000, null=True)),
                ('mailverifycode', models.CharField(blank=True, max_length=1000, null=True)),
                ('twofactorenabled', models.BooleanField(verbose_name='twofactorenabled')),
                ('profilephoto', models.FileField(blank=True, null=True, upload_to='')),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('darchbalance', models.DecimalField(decimal_places=8, default='0', max_digits=25)),
                ('ethbalance', models.DecimalField(decimal_places=8, default='0', max_digits=25)),
                ('isitverified', models.CharField(blank=True, default='normal', max_length=1000, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='urllist',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.User'),
        ),
        migrations.AddField(
            model_name='urllist',
            name='whichproductsurl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ProductList'),
        ),
        migrations.AddField(
            model_name='transmitlist',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trequester_name', to='core.User'),
        ),
        migrations.AddField(
            model_name='transmitlist',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tsenders_name', to='core.User'),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requesters_name', to='core.User'),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='senders_name', to='core.User'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='king',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.User'),
        ),
        migrations.AddField(
            model_name='commentandstarlist',
            name='csender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.User'),
        ),
    ]
